### ISSUE TITLE
MOD-LTR501.ino  bug?

### ISSUE THREAD

**Issue by mchobby** [OLIMEX/UEXT-MODULES#2]
In the file:
UEXT-MODULES/MOD-LTR-501ALS/ARDUINO EXAMPLE/MOD-LTR501.ino

the Lux Sensor is read with
```
if(stat & 0x04){
      //ALS new data
      unsigned char data[4];
      for(int i = 0; i < 4; i++){
        data[i] = Read(0x88 + i);
      }
      ADC_1 = (data[1] << 8) | data[0];
      ADC_0 = (data[3] << 8) | data[1];
      Serial.print("ALS1: ");
      Serial.print(ADC_1, DEC);
      Serial.println(" LUX");
      Serial.print("ALS0: ");
      Serial.print(ADC_0, DEC);
      Serial.println(" LUX");
}
```
Regarding the datasheet, ADC_0 is stored in registers 0x8A (lower byte) and 0x8B (higher byte)

So the ADC_0 should instead be: 
` ADC_0 = (data[3] << 8) | data[2]; `

Am I right ?

**Comment by d3v1c3nv11** [comment]
Yes You are right. Corrected.
